onlyBuiltDependencies:
  - esbuild
allowBuilds:
  esbuild: true
  workerd: false
minimumReleaseAgeExclude:
  - "@prisma/orm-family-sql@8.0.0-rc.16"
  - "@prisma/orm-framework@8.0.0-rc.16"
  - "@prisma/orm-postgres@8.0.0-rc.16"
  - "@prisma/orm-target-postgres@8.0.0-rc.16"
  - "@prisma/orm-toolchain@8.0.0-rc.16"
  - "@prisma/composer-cli@0.28.0"
  - "@prisma/composer@0.28.0"
  - prisma@8.0.0-rc.21
